const CLASS_INFO={
  "テルペン類":{color:"#2e7d32",light:"#e8f5e9"},
  "エステル類":{color:"#ef6c00",light:"#fff3e0"},
  "アルデヒド類":{color:"#9a7600",light:"#fff8d8"},
  "ケトン類":{color:"#c62828",light:"#ffebee"},
  "アルコール類":{color:"#1565c0",light:"#e3f2fd"},
  "フェノール類":{color:"#6a1b9a",light:"#f3e5f5"},
  "含硫化合物":{color:"#455a64",light:"#eceff1"},
  "その他":{color:"#795548",light:"#efebe9"}
};
const S={c:[],mode:"learn",questionCount:10,q:[],i:0,stage:0,score:0,totalSteps:0,miss:[],answered:false,stats:JSON.parse(localStorage.getItem("aromaStats")||"{}")};
const $=id=>document.getElementById(id),screens=[...document.querySelectorAll(".screen")];
function show(id){screens.forEach(s=>s.classList.toggle("active",s.id===id));scrollTo({top:0,behavior:"smooth"})}
function shuffle(items){const a=Array.from(items);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function classInfo(c){return CLASS_INFO[c.class_group]||CLASS_INFO["その他"]}
function applyClassTheme(el,c){const t=classInfo(c);el.style.setProperty("--class-color",t.color);el.style.setProperty("--class-light",t.light)}
function rec(id){return S.stats[id]||{correct:0,wrong:0}}
function save(){localStorage.setItem("aromaStats",JSON.stringify(S.stats))}
function isMaster(c){const r=rec(c.id),t=r.correct+r.wrong;return r.correct>=3&&r.correct/Math.max(1,t)>=.75}
function isReview(c){const r=rec(c.id),t=r.correct+r.wrong;return r.wrong>0&&(r.correct<3||r.correct/t<.75)}
function home(){const m=S.c.filter(isMaster).length,p=S.c.length?Math.round(m/S.c.length*100):0;$('mastery').textContent=p+'%';$('ring').style.setProperty('--p',p+'%');$('reviewN').textContent='復習対象 '+S.c.filter(isReview).length+'成分'}
function renderLegend(){$('legend').innerHTML=Object.entries(CLASS_INFO).filter(([k])=>k!=="その他").map(([name,t])=>`<span style="--tag-color:${t.color};--tag-light:${t.light}">${name}</span>`).join('')}
function start(mode){let pool=[...S.c];if(mode==='review'){const r=pool.filter(isReview);pool=r.length>=4?r:pool;S.mode='learn'}else S.mode=mode;S.q=shuffle(pool).slice(0,S.questionCount);S.i=0;S.stage=0;S.score=0;S.miss=[];S.answered=false;S.totalSteps=S.mode==='learn'?S.q.length*2:S.q.length;show('quiz');renderQ()}
function distract(a){const same=S.c.filter(c=>c.id!==a.id&&c.class_group===a.class_group),other=S.c.filter(c=>c.id!==a.id&&c.class_group!==a.class_group);return shuffle([...shuffle(same).slice(0,2),...shuffle(other)]).slice(0,3)}
function currentStep(){return S.mode==='learn'?S.i*2+S.stage:S.i}
function renderQ(){const a=S.q[S.i],isStructure=S.mode==='structure'||(S.mode==='learn'&&S.stage===1),opts=shuffle([a,...distract(a)]);S.answered=false;$('feedback').className='feedback hidden';applyClassTheme($('questionCard'),a);$('counter').textContent=`${currentStep()+1} / ${S.totalSteps}`;$('bar').style.width=currentStep()/S.totalSteps*100+'%';$('stageBadge').textContent=S.mode==='learn'?(S.stage===0?'STEP 1　香り → 成分名':'STEP 2　成分名 → 構造式'):'';$('stageBadge').style.display=S.mode==='learn'?'inline-flex':'none';$('qtype').textContent=isStructure?'STRUCTURE QUIZ':'ODOR QUIZ';$('qtext').textContent=isStructure?`${a.name_ja}の構造式はどれ？`:a.odor;$('hint').textContent=isStructure?'正しい構造式を選んでください。':`代表的な由来：${a.sources}`;$('choices').innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.className='choice';b.dataset.id=o.id;if(isStructure){b.classList.add('structure');b.innerHTML=`<img src="${o.structure}" alt="${o.name_ja}の構造式候補">`}else{b.innerHTML=`<strong>${o.name_ja}</strong><br><small>${o.name_en}</small>`}b.onclick=()=>answer(o.id,b,isStructure);$('choices').appendChild(b)})}
function answer(id,btn,isStructure){if(S.answered)return;S.answered=true;const a=S.q[S.i],ok=id===a.id,r=rec(a.id);if(ok){S.score++;r.correct++}else{r.wrong++;S.miss.push(a)}S.stats[a.id]=r;save();document.querySelectorAll('.choice').forEach(b=>{b.disabled=true;if(b.dataset.id===a.id)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');const fb=$('feedback');fb.className='feedback '+(ok?'good':'bad');applyClassTheme(fb,a);$('mark').textContent=ok?'✓':'×';$('flabel').textContent=ok?'正解です':'正解はこちら';$('ftitle').textContent=`${a.name_ja}（${a.name_en}）`;$('fgroup').textContent=a.class_group;$('fimg').src=a.structure;$('fodor').textContent=a.odor;$('fsrc').textContent=a.sources;$('fcat').textContent=`${a.category}｜${a.formula}｜分子量 ${a.molecular_weight}`;$('ffeat').textContent=`${a.functional_group}。${a.feature}`;const last=currentStep()===S.totalSteps-1;$('next').textContent=last?'結果を見る':(S.mode==='learn'&&S.stage===0?'構造式へ進む':'次の問題');$('bar').style.width=(currentStep()+1)/S.totalSteps*100+'%';fb.scrollIntoView({behavior:'smooth',block:'nearest'})}
function advance(){if(S.mode==='learn'&&S.stage===0){S.stage=1;renderQ();scrollTo({top:0,behavior:'smooth'});return}if(S.i<S.q.length-1){S.i++;S.stage=0;renderQ();scrollTo({top:0,behavior:'smooth'})}else finish()}
function finish(){$('score').textContent=S.score;$('scoreDenom').textContent=`/ ${S.totalSteps}`;const ratio=S.score/S.totalSteps;$('resultMsg').textContent=ratio===1?'全問正解です。':ratio>=.8?'よくできました。香りと構造の結びつきが身についています。':ratio>=.6?'基本はつかめています。分類色と官能基に注目して復習しましょう。':'図鑑で香り・分類・構造式を順に確認して再挑戦しましょう。';const u=[...new Map(S.miss.map(c=>[c.id,c])).values()];$('missed').innerHTML=u.length?'<h3>今回の復習対象</h3>'+u.map(c=>`<div class="missItem" style="--class-color:${classInfo(c).color}"><strong>${c.name_ja}</strong><span>${c.class_group}</span><p>${c.feature}</p></div>`).join(''):'';show('result');home()}
function library(){const q=$('search').value.toLowerCase(),cat=$('cat').value,list=S.c.filter(c=>(!q||`${c.name_ja} ${c.name_en} ${c.odor} ${c.sources} ${c.category} ${c.functional_group}`.toLowerCase().includes(q))&&(!cat||c.class_group===cat));$('cards').innerHTML=list.map(c=>{const t=classInfo(c);return `<article class="card" style="--class-color:${t.color};--class-light:${t.light}"><img src="${c.structure}" alt="${c.name_ja}の構造式"><div><span class="tag">${c.class_group}</span><h3>${c.name_ja}</h3><p class="en">${c.name_en}｜${c.formula}</p><p><b>香り：</b>${c.odor}</p><p><b>由来：</b>${c.sources}</p><p><b>詳細分類：</b>${c.category}</p><p><b>官能基：</b>${c.functional_group}</p><p>${c.feature}</p></div></article>`}).join('')}
function stats(){let tc=0,tw=0,m=0,rows=S.c.map(c=>{const r=rec(c.id),t=r.correct+r.wrong,a=t?Math.round(r.correct/t*100):0;tc+=r.correct;tw+=r.wrong;if(isMaster(c))m++;return{c,t,a}}).sort((x,y)=>y.t-x.t);const total=tc+tw;$('total').textContent=total;$('accuracy').textContent=total?Math.round(tc/total*100)+'%':'0%';$('mastered').textContent=m;$('statRows').innerHTML=rows.map(x=>`<div class="statRow"><strong>${x.c.name_ja}</strong><div class="miniBar"><span style="width:${x.a}%;background:${classInfo(x.c).color}"></span></div><small>${x.t?x.a+'%':'未回答'}</small></div>`).join('')}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('next').onclick=advance;$('quit').onclick=()=>{home();show('home')};$('retry').onclick=()=>start(S.mode);$('homeBtn').onclick=()=>{home();show('home')};$('libraryBtn').onclick=()=>{library();show('library')};$('libBack').onclick=()=>show('home');$('search').oninput=library;$('cat').onchange=library;$('statsBtn').onclick=()=>{stats();show('stats')};$('statsBack').onclick=()=>show('home');$('reset').onclick=()=>{if(confirm('すべての学習記録を削除しますか？')){S.stats={};save();stats();home()}};
fetch('data/compounds.json').then(r=>{if(!r.ok)throw new Error('data');return r.json()}).then(d=>{S.c=d;Object.keys(CLASS_INFO).filter(k=>d.some(c=>c.class_group===k)).forEach(c=>$('cat').insertAdjacentHTML('beforeend',`<option>${c}</option>`));renderLegend();home();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{})}).catch(()=>$('home').innerHTML='<p>データを読み込めませんでした。Webサーバー上で開いてください。</p>');
